provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-mgcv:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-prevalence-predictor-mgcv:0.0.4
