provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-mgcv:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-prevalence-predictor-mgcv:0.1.3
    environment:
      write_timeout: 900
      read_timeout: 900
      exec_timeout: 900
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.zero: true
