provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-prevalence-predictor-mgcv:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-prevalence-predictor-mgcv:0.1.2
    environment:
      write_timeout: 600
      read_timeout: 600
      exec_timeout: 600
      combine_output: false
      write_debug: true
    labels:
      com.openfaas.scale.zero: true
